import { useCallback, useEffect, useState, type FormEvent } from 'react';
import { adminApi, type AdminUser, type WorkspaceMember } from '../api/cloudApi';
import FormModal from '../components/FormModal';
import { useSession } from '../contexts/SessionContext';

export default function AdminUsersPage() {
  const { workspaceId, principal } = useSession(); const isAdmin = principal?.platformRoles.includes('admin');
  const [users, setUsers] = useState<AdminUser[]>([]), [members, setMembers] = useState<WorkspaceMember[]>([]), [showCreate, setShowCreate] = useState(false), [showAdd, setShowAdd] = useState(false), [email, setEmail] = useState(''), [name, setName] = useState(''), [role, setRole] = useState<WorkspaceMember['role']>('client'), [userId, setUserId] = useState(''), [error, setError] = useState('');
  const load = useCallback(async () => { if (!workspaceId || !isAdmin) return; try { const [u, m] = await Promise.all([adminApi.users(), adminApi.members(workspaceId)]); setUsers(u); setMembers(m); setError(''); } catch (e) { setError((e as Error).message); } }, [workspaceId, isAdmin]); useEffect(() => { void load(); }, [load]);
  const nonMembers = users.filter((u) => !members.some((m) => m.user_id === u.id));
  async function create(e: FormEvent) { e.preventDefault(); if (!workspaceId) return; await adminApi.createUser({ email, displayName: name, status: 'invited', workspaceId, role }); setShowCreate(false); setName(''); setEmail(''); await load(); }
  async function add(e: FormEvent) { e.preventDefault(); if (!workspaceId) return; await adminApi.addMember(workspaceId, userId, role); setShowAdd(false); await load(); }
  if (!isAdmin) return <div className="alert alert-danger">Platform administrator access is required.</div>;
  return <>
    <div className="page-header"><div><h1>Admin Users</h1><p className="page-subtitle">Give each account the right access to this workspace.</p></div><div className="actions"><button className="btn btn-outline" disabled={!nonMembers.length} onClick={() => { setUserId(nonMembers[0]?.id ?? ''); setShowAdd(true); }}>Add existing user</button><button className="btn btn-primary" onClick={() => setShowCreate(true)}>Provision user</button></div></div>
    {error && <div className="alert alert-danger">{error}</div>}
    <h2 className="h4">Workspace members</h2><div className="table-wrap"><table><thead><tr><th>User</th><th>Account</th><th>Workspace role</th><th>Membership</th><th>Action</th></tr></thead><tbody>{members.map((member) => <tr key={member.user_id}><td><strong>{member.display_name}</strong><br/><span className="muted">{member.email_display}</span></td><td>{member.user_status}</td><td><select value={member.role} onChange={async (e) => { if (workspaceId) { await adminApi.updateMember(workspaceId, member.user_id, { role: e.target.value as WorkspaceMember['role'] }); await load(); } }}><option value="owner">Owner</option><option value="coach">Coach</option><option value="client">Client</option></select></td><td>{member.status}</td><td>{member.role !== 'owner' && <button className="btn btn-danger btn-xs" onClick={async () => { if (workspaceId) { await adminApi.removeMember(workspaceId, member.user_id); await load(); } }}>Remove</button>}</td></tr>)}</tbody></table></div>
    <h2 className="h4 mt-4">Other global users</h2><div className="table-wrap"><table><thead><tr><th>User</th><th>Status</th><th>Platform role</th></tr></thead><tbody>{nonMembers.map((user) => <tr key={user.id}><td><strong>{user.display_name}</strong><br/><span className="muted">{user.email_display}</span></td><td>{user.status}</td><td>{user.platform_roles ?? '—'}</td></tr>)}</tbody></table></div>
    <FormModal show={showAdd} onHide={() => setShowAdd(false)} title="Add existing global user" onSubmit={add} submitDisabled={!userId}><div className="form-group"><label>User</label><select value={userId} onChange={(e) => setUserId(e.target.value)}>{nonMembers.map((u) => <option key={u.id} value={u.id}>{u.display_name} — {u.email_display}</option>)}</select></div><div className="form-group"><label>Workspace role</label><select value={role} onChange={(e) => setRole(e.target.value as WorkspaceMember['role'])}><option value="owner">Owner</option><option value="coach">Coach</option><option value="client">Client</option></select></div></FormModal>
    <FormModal show={showCreate} onHide={() => setShowCreate(false)} title="Provision beta user" onSubmit={create} submitDisabled={!name.trim() || !email.trim()}><div className="form-group"><label>Name</label><input value={name} onChange={(e) => setName(e.target.value)} /></div><div className="form-group"><label>Verified email</label><input type="email" value={email} onChange={(e) => setEmail(e.target.value)} /></div><div className="form-group"><label>Workspace role</label><select value={role} onChange={(e) => setRole(e.target.value as WorkspaceMember['role'])}><option value="owner">Owner</option><option value="coach">Coach</option><option value="client">Client</option></select></div></FormModal>
  </>;
}
