import { useCallback, useEffect, useState, type FormEvent } from 'react';
import { adminApi, type AdminUser, type AdminWorkspace, type WorkspaceMember } from '../api/cloudApi';
import FormModal from '../components/FormModal';
import { useSession } from '../contexts/SessionContext';

export default function AdminUsersPage() {
  const { workspaceId, principal } = useSession();
  const [users, setUsers] = useState<AdminUser[]>([]); const [members, setMembers] = useState<WorkspaceMember[]>([]);
  const [workspace, setWorkspace] = useState<AdminWorkspace | null>(null);
  const [showCreate, setShowCreate] = useState(false); const [email, setEmail] = useState(''); const [name, setName] = useState(''); const [role, setRole] = useState<WorkspaceMember['role']>('client'); const [error, setError] = useState<string | null>(null);
  const isAdmin = principal?.platformRoles.includes('admin');
  const load = useCallback(async () => { if (!workspaceId || !isAdmin) return; try { const [nextUsers, nextMembers, nextWorkspace] = await Promise.all([adminApi.users(), adminApi.members(workspaceId), adminApi.workspace(workspaceId)]); setUsers(nextUsers); setMembers(nextMembers); setWorkspace(nextWorkspace); setError(null); } catch (reason) { setError((reason as Error).message); } }, [workspaceId, isAdmin]);
  useEffect(() => { void load(); }, [load]);
  const create = async (event: FormEvent) => { event.preventDefault(); if (!workspaceId) return; try { await adminApi.createUser({ email, displayName: name, status: 'invited', workspaceId, role }); setEmail(''); setName(''); setShowCreate(false); await load(); } catch (reason) { setError((reason as Error).message); } };
  if (!isAdmin) return <div className="alert alert-danger">Forbidden: platform administrator access is required.</div>;
  return <>
    <div className="page-header"><div><h1>Admin Users</h1><p className="page-subtitle">Manually provision beta accounts. Public signup remains disabled.</p></div><div className="actions"><button className={`btn ${workspace?.legal_hold_at ? 'btn-danger' : 'btn-outline'}`} onClick={async () => { if (!workspaceId || !workspace) return; const enabled = !workspace.legal_hold_at; const reason = enabled ? window.prompt('Reason for legal hold') : undefined; if (enabled && !reason) return; try { setWorkspace(await adminApi.setLegalHold(workspaceId, enabled, reason ?? undefined)); } catch (cause) { setError((cause as Error).message); } }}>{workspace?.legal_hold_at ? 'Clear legal hold' : 'Enable legal hold'}</button><button className="btn btn-primary" onClick={() => setShowCreate(true)}>Provision user</button></div></div>
    {workspace?.legal_hold_at && <div className="alert alert-warning">Legal hold active since {workspace.legal_hold_at}: {workspace.legal_hold_reason}. Scheduled workspace history deletion and workspace deletion are blocked.</div>}
    {error && <div className="alert alert-danger">{error} <button className="inline-link" onClick={() => void load()}>Retry</button></div>}
    <div className="table-wrap"><table><thead><tr><th>User</th><th>Status</th><th>Workspace role</th><th>Platform role</th><th>Action</th></tr></thead><tbody>{users.map((user) => { const member = members.find((item) => item.user_id === user.id); return <tr key={user.id}><td><strong>{user.display_name}</strong><br /><span className="muted">{user.email_display}</span></td><td><span className={`status status-${user.status}`}>{user.status}</span></td><td>{member ? <select value={member.role} onChange={async (event) => { if (workspaceId) { await adminApi.updateMember(workspaceId, user.id, { role: event.target.value as WorkspaceMember['role'] }); await load(); } }}><option value="owner">Owner</option><option value="coach">Coach</option><option value="client">Client</option></select> : '—'}</td><td>{user.platform_roles ?? '—'}</td><td><button className="btn btn-outline btn-xs" onClick={async () => { await adminApi.updateUser(user.id, { status: user.status === 'disabled' ? 'active' : 'disabled' }); await load(); }}>{user.status === 'disabled' ? 'Enable' : 'Disable'}</button></td></tr>; })}</tbody></table></div>
    <FormModal show={showCreate} onHide={() => setShowCreate(false)} title="Provision beta user" onSubmit={create} submitDisabled={!name.trim() || !email.trim()}><div className="form-group"><label>Name</label><input value={name} onChange={(event) => setName(event.target.value)} /></div><div className="form-group"><label>Verified email</label><input type="email" value={email} onChange={(event) => setEmail(event.target.value)} /></div><div className="form-group"><label>Workspace role</label><select value={role} onChange={(event) => setRole(event.target.value as WorkspaceMember['role'])}><option value="owner">Owner</option><option value="coach">Coach</option><option value="client">Client</option></select></div><p className="muted">The user is created as invited and receives a local identity for development. A future provider may link only after verified-email matching.</p></FormModal>
  </>;
}
