import { useCallback, useEffect, useState, type FormEvent } from 'react';
import { Link } from 'react-router-dom';
import { adminApi, clientsApi, programsApi, type ClientRelationship, type WorkspaceMember } from '../api/cloudApi';
import FormModal from '../components/FormModal';
import ConfirmModal from '../components/ConfirmModal';
import { useSession } from '../contexts/SessionContext';
import type { Program } from '../types/cloud';

export default function ClientsPage() {
  const { workspaceId, principal } = useSession(); const access = principal?.availableWorkspaces.find((item) => item.workspaceId === workspaceId);
  const [clients, setClients] = useState<ClientRelationship[]>([]), [members, setMembers] = useState<WorkspaceMember[]>([]), [programs, setPrograms] = useState<Program[]>([]), [clientPrograms, setClientPrograms] = useState<Record<string, Program[]>>({}), [error, setError] = useState('');
  const [showRelationship, setShowRelationship] = useState(false), [showCreate, setShowCreate] = useState(false), [showCopy, setShowCopy] = useState(false), [clientId, setClientId] = useState(''), [sourceProgram, setSourceProgram] = useState(''), [name, setName] = useState(''), [includeExecuted, setIncludeExecuted] = useState(false), [removing, setRemoving] = useState<ClientRelationship|null>(null);
  const load = useCallback(async () => { if (!workspaceId) return; try { const [nextClients, nextMembers, nextPrograms] = await Promise.all([clientsApi.list(workspaceId), adminApi.members(workspaceId), programsApi.list(workspaceId)]); const byClient: Record<string, Program[]> = {}; await Promise.all(nextClients.map(async (client) => { byClient[client.client_user_id] = await programsApi.list(workspaceId, 'current', client.client_user_id); })); setClients(nextClients); setMembers(nextMembers); setPrograms(nextPrograms); setClientPrograms(byClient); setError(''); } catch (e) { setError((e as Error).message); } }, [workspaceId]);
  useEffect(() => { void load(); }, [load]);
  const availableClients = members.filter((m) => m.role === 'client' && m.status === 'active' && !clients.some((c) => c.client_user_id === m.user_id));
  if (access?.role === 'client') return <div className="alert alert-danger">Client management is limited to coaches and owners.</div>;
  async function addRelationship(e: FormEvent) { e.preventDefault(); if (!workspaceId) return; await clientsApi.add(workspaceId, clientId); setShowRelationship(false); await load(); }
  async function createProgram(e: FormEvent) { e.preventDefault(); if (!workspaceId) return; await programsApi.create(workspaceId, { name, ownerUserId: clientId }); setShowCreate(false); setName(''); await load(); }
  async function copyProgram(e: FormEvent) { e.preventDefault(); if (!workspaceId) return; await programsApi.copy(workspaceId, sourceProgram, { name, targetOwnerUserId: clientId, includeExecutedValues: includeExecuted }); setShowCopy(false); setName(''); await load(); }
  return <>
    <div className="page-header"><div><h1>Clients</h1><p className="page-subtitle">Build a plan for each person you coach.</p></div><button className="btn btn-outline" disabled={!availableClients.length} onClick={() => { setClientId(availableClients[0]?.user_id ?? ''); setShowRelationship(true); }}>Add client</button></div>
    {error && <div className="alert alert-danger">{error}</div>}
    <div className="row g-3">{clients.map((client) => <div className="col-12 col-lg-6" key={client.id}><article className="card"><div className="section-header"><div><h2>{client.display_name}</h2><p className="muted">{client.email_display}</p></div><span className="badge">{client.program_count} programs</span></div>
      <div className="workout-list">{(clientPrograms[client.client_user_id] ?? []).map((program) => <Link className="workout-row" key={program.id} to={`/programs/${program.id}`}><span>{program.name}</span><span className="muted">Open</span></Link>)}</div>
      <div className="actions mt-3"><button className="btn btn-outline btn-sm" onClick={() => { setClientId(client.client_user_id); setName(`${client.display_name} program`); setShowCreate(true); }}>Create program</button><button className="btn btn-primary btn-sm" disabled={!programs.length} onClick={() => { setClientId(client.client_user_id); setSourceProgram(programs[0]?.id ?? ''); setName(`${programs[0]?.name ?? 'Program'} copy`); setIncludeExecuted(false); setShowCopy(true); }}>Copy program</button>{access?.role === 'owner' || access?.role === 'admin' ? <button className="btn btn-danger btn-sm" onClick={() => setRemoving(client)}>Remove client</button> : <button className="btn btn-outline btn-sm" onClick={async () => { if (workspaceId) { await clientsApi.remove(workspaceId, client.id); await load(); } }}>End relationship</button>}</div>
    </article></div>)}</div>
    {!clients.length && <div className="empty-state"><h2>No clients</h2><p>Add a relationship to an existing client member.</p></div>}
    <FormModal show={showRelationship} onHide={() => setShowRelationship(false)} title="Add client relationship" onSubmit={addRelationship} submitDisabled={!clientId}><div className="form-group"><label>Client member</label><select value={clientId} onChange={(e) => setClientId(e.target.value)}>{availableClients.map((m) => <option key={m.user_id} value={m.user_id}>{m.display_name}</option>)}</select></div></FormModal>
    <FormModal show={showCreate} onHide={() => setShowCreate(false)} title="Create client program" onSubmit={createProgram} submitDisabled={!name.trim()}><div className="form-group"><label>Name</label><input value={name} onChange={(e) => setName(e.target.value)} /></div></FormModal>
    <FormModal show={showCopy} onHide={() => setShowCopy(false)} title="Copy program for client" onSubmit={copyProgram} submitDisabled={!sourceProgram || !name.trim()}><div className="form-group"><label>Source program</label><select value={sourceProgram} onChange={(e) => { setSourceProgram(e.target.value); const source = programs.find((p) => p.id === e.target.value); if (source) setName(`${source.name} copy`); }}>{programs.map((p) => <option key={p.id} value={p.id}>{p.name} — {p.owner_name}</option>)}</select></div><div className="form-group"><label>Copy name</label><input value={name} onChange={(e) => setName(e.target.value)} /></div><label className="form-check"><input type="checkbox" checked={includeExecuted} onChange={(e) => setIncludeExecuted(e.target.checked)} /> Include executed values and athlete notes</label></FormModal>
    <ConfirmModal show={Boolean(removing)} onHide={() => setRemoving(null)} title="Remove client from workspace" message="This deletes the client’s current programs and relationship after history capture, then removes only this workspace membership. The global user remains." confirmLabel="Remove" onConfirm={async () => { if (workspaceId && removing) { await adminApi.removeMember(workspaceId, removing.client_user_id); setRemoving(null); await load(); } }} />
  </>;
}
