import { useCallback, useEffect, useState, type FormEvent } from 'react';
import { Link } from 'react-router-dom';
import { adminApi, assignmentsApi, programsApi, type Assignment, type ClientRelationship, type WorkspaceMember } from '../api/cloudApi';
import FormModal from '../components/FormModal';
import ConfirmModal from '../components/ConfirmModal';
import { useSession } from '../contexts/SessionContext';
import type { Program } from '../types/cloud';

export default function ClientsPage() {
  const { workspaceId, principal } = useSession();
  const membership = principal?.memberships.find((item) => item.workspaceId === workspaceId);
  const [clients, setClients] = useState<ClientRelationship[]>([]); const [assignments, setAssignments] = useState<Assignment[]>([]); const [templates, setTemplates] = useState<Program[]>([]); const [members, setMembers] = useState<WorkspaceMember[]>([]);
  const [showAssign, setShowAssign] = useState(false); const [showRelationship, setShowRelationship] = useState(false); const [clientId, setClientId] = useState(''); const [templateId, setTemplateId] = useState(''); const [name, setName] = useState(''); const [removing, setRemoving] = useState<ClientRelationship | null>(null); const [error, setError] = useState<string | null>(null);
  const load = useCallback(async () => { if (!workspaceId) return; try { const [nextClients, nextAssignments, allPrograms, nextMembers] = await Promise.all([assignmentsApi.clients(workspaceId), assignmentsApi.assignments(workspaceId), programsApi.list(workspaceId), adminApi.members(workspaceId)]); setClients(nextClients); setAssignments(nextAssignments); setTemplates(allPrograms.filter((item) => item.kind === 'template')); setMembers(nextMembers); setError(null); } catch (reason) { setError((reason as Error).message); } }, [workspaceId]);
  useEffect(() => { void load(); }, [load]);
  const assign = async (event: FormEvent) => { event.preventDefault(); if (!workspaceId) return; try { await assignmentsApi.create(workspaceId, { sourceProgramId: templateId, clientUserId: clientId, name: name || undefined }); setShowAssign(false); setName(''); await load(); } catch (reason) { setError((reason as Error).message); } };
  const addRelationship = async (event: FormEvent) => { event.preventDefault(); if (!workspaceId) return; try { await assignmentsApi.addClient(workspaceId, clientId); setShowRelationship(false); await load(); } catch (reason) { setError((reason as Error).message); } };
  const availableClients = members.filter((item) => item.role === 'client' && item.status === 'active' && !clients.some((client) => client.client_user_id === item.user_id));
  if (membership?.role === 'client') return <div className="alert alert-danger">Forbidden: client management is limited to coaches and owners.</div>;
  return <>
    <div className="page-header"><div><h1>Clients</h1><p className="page-subtitle">Coach relationships and independent assigned-program copies.</p></div><div className="actions"><button className="btn btn-outline" disabled={!availableClients.length} onClick={() => { setClientId(availableClients[0]?.user_id ?? ''); setShowRelationship(true); }}>Add relationship</button><button className="btn btn-primary" disabled={!clients.length || !templates.length} onClick={() => { setClientId(clients[0]?.client_user_id ?? ''); setTemplateId(templates[0]?.id ?? ''); setShowAssign(true); }}>Assign template</button></div></div>
    {error && <div className="alert alert-danger">{error} <button className="inline-link" onClick={() => void load()}>Retry</button></div>}
    <div className="row g-3">{clients.map((client) => <div className="col-12 col-lg-6" key={client.id}><article className="card"><div className="section-header"><div><h2>{client.display_name}</h2><p className="muted">{client.email_display}</p></div><span className="badge">{client.active_assignments} active</span></div><div className="assignment-list">{assignments.filter((item) => item.client_user_id === client.client_user_id).map((item) => <div className="assignment-row" key={item.id}><div><Link to={`/programs/${item.assigned_program_id}`}>{item.assigned_program_name}</Link><p className="muted">From {item.source_program_name} revision {item.source_revision}</p></div><div className="actions"><button className="btn btn-outline btn-xs" onClick={async () => { if (workspaceId) { await assignmentsApi.update(workspaceId, item.id, { status: item.status === 'active' ? 'completed' : 'active' }); await load(); } }}>{item.status === 'active' ? 'Complete' : 'Reopen'}</button><button className="btn btn-danger btn-xs" onClick={async () => { if (workspaceId && window.confirm('Delete this assigned copy and its current plan/results after history capture?')) { await assignmentsApi.remove(workspaceId, item.id); await load(); } }}>Delete</button></div></div>)}</div>{membership?.role === 'owner' ? <button className="btn btn-danger btn-sm" onClick={() => setRemoving(client)}>Remove client</button> : <button className="btn btn-outline btn-sm" onClick={async () => { if (workspaceId) { await assignmentsApi.removeClientRelationship(workspaceId, client.id); await load(); } }}>End relationship</button>}</article></div>)}</div>
    {clients.length === 0 && <div className="empty-state"><h2>No active clients</h2><p>Provision a client membership, then add a coach relationship here.</p></div>}
    <FormModal show={showAssign} onHide={() => setShowAssign(false)} title="Assign program copy" onSubmit={assign} submitDisabled={!clientId || !templateId}><div className="form-group"><label>Client</label><select value={clientId} onChange={(event) => setClientId(event.target.value)}>{clients.map((client) => <option key={client.client_user_id} value={client.client_user_id}>{client.display_name}</option>)}</select></div><div className="form-group"><label>Template</label><select value={templateId} onChange={(event) => setTemplateId(event.target.value)}>{templates.map((template) => <option key={template.id} value={template.id}>{template.name}</option>)}</select></div><div className="form-group"><label>Assigned name (optional)</label><input value={name} onChange={(event) => setName(event.target.value)} /></div><p className="muted">A D1 copy is created. Editing it will not change the template or any other assignment.</p></FormModal>
    <FormModal show={showRelationship} onHide={() => setShowRelationship(false)} title="Add client relationship" onSubmit={addRelationship} submitDisabled={!clientId}><div className="form-group"><label>Client member</label><select value={clientId} onChange={(event) => setClientId(event.target.value)}>{availableClients.map((client) => <option key={client.user_id} value={client.user_id}>{client.display_name}</option>)}</select></div></FormModal>
    <ConfirmModal show={Boolean(removing)} onHide={() => setRemoving(null)} title="Remove client from workspace" message="This removes current relationships, assignments, client-specific plans, sessions/results, and membership after history capture. It does not delete the global user." confirmLabel="Remove" onConfirm={async () => { if (workspaceId && removing) { await adminApi.removeMember(workspaceId, removing.client_user_id); await load(); } }} />
  </>;
}
