import { useCallback, useEffect, useState, type FormEvent } from 'react';
import { Link, useNavigate, useParams } from 'react-router-dom';
import { adminApi, programsApi, type MesocycleSummary, type WorkspaceMember } from '../api/cloudApi';
import FormModal from '../components/FormModal';
import ConfirmModal from '../components/ConfirmModal';
import { useSession } from '../contexts/SessionContext';
import type { Mesocycle, Program, Workout } from '../types/cloud';

interface CycleRow extends Mesocycle { workouts: Workout[]; summary?: MesocycleSummary }
export default function ProgramPage() {
  const { programId = '' } = useParams(), navigate = useNavigate(); const { workspaceId, principal } = useSession(); const access = principal?.availableWorkspaces.find((item) => item.workspaceId === workspaceId); const canPlan = access?.role !== 'client';
  const [row, setRow] = useState<Program|null>(null), [cycles, setCycles] = useState<CycleRow[]>([]), [members, setMembers] = useState<WorkspaceMember[]>([]), [programs, setPrograms] = useState<Program[]>([]), [summary, setSummary] = useState<Record<string, number>>({}), [error, setError] = useState('');
  const [cycleModal, setCycleModal] = useState(false), [workoutCycle, setWorkoutCycle] = useState<string|null>(null), [copyProgram, setCopyProgram] = useState(false), [copyCycle, setCopyCycle] = useState<Mesocycle|null>(null), [deleteOpen, setDeleteOpen] = useState(false);
  const [name, setName] = useState(''), [startDate, setStartDate] = useState(new Date().toISOString().slice(0,10)), [dayOffset, setDayOffset] = useState(0), [targetOwner, setTargetOwner] = useState(''), [targetProgram, setTargetProgram] = useState(''), [includeExecuted, setIncludeExecuted] = useState(false);
  const load = useCallback(async () => { if (!workspaceId) return; try { const [p, m, s, allPrograms] = await Promise.all([programsApi.get(workspaceId, programId), programsApi.mesocycles(workspaceId, programId), programsApi.summary(workspaceId, programId), programsApi.list(workspaceId)]); const expanded = await Promise.all(m.map(async (cycle) => ({ ...cycle, workouts: await programsApi.workouts(workspaceId, programId, cycle.id), summary: await programsApi.mesocycleSummary(workspaceId, programId, cycle.id) }))); setRow(p); setCycles(expanded); setSummary(s); setPrograms(allPrograms); if (canPlan) { const next = await adminApi.members(workspaceId); setMembers(next); setTargetOwner(p.owner_user_id); setTargetProgram(p.id); } setError(''); } catch (e) { setError((e as Error).message); } }, [workspaceId, programId, canPlan]);
  useEffect(() => { void load(); }, [load]);
  async function addCycle(e: FormEvent) { e.preventDefault(); if (!workspaceId) return; await programsApi.createMesocycle(workspaceId, programId, { name, mesocycleLength: 7, startDate }); setName(''); setCycleModal(false); await load(); }
  async function addWorkout(e: FormEvent) { e.preventDefault(); if (!workspaceId || !workoutCycle) return; await programsApi.createWorkout(workspaceId, programId, workoutCycle, { name, dayOffset }); setName(''); setWorkoutCycle(null); await load(); }
  if (error && !row) return <div className="alert alert-danger">{error}</div>; if (!row) return <div className="empty-state">Loading program…</div>;
  return <>
    <div className="breadcrumb"><Link to="/">Programs</Link><span>/</span>{row.name}</div>
    <div className="page-header"><div><h1>{row.name}</h1><p className="muted">Owned by {row.owner_name}</p></div>{canPlan && <div className="actions"><button className="btn btn-outline btn-sm" onClick={() => { setName(`${row.name} copy`); setTargetOwner(row.owner_user_id); setIncludeExecuted(false); setCopyProgram(true); }}>Copy program</button><button className="btn btn-danger btn-sm" onClick={() => setDeleteOpen(true)}>Delete</button></div>}</div>
    {error && <div className="alert alert-danger">{error}</div>}
    <div className="stats-row">{Object.entries(summary).map(([label, value]) => <div className="stat" key={label}><strong>{value}</strong><span>{label.replace('_',' ')}</span></div>)}</div>
    <div className="section-header"><h2>Mesocycles</h2>{canPlan && <button className="btn btn-primary btn-sm" onClick={() => { setName(''); setCycleModal(true); }}>Add mesocycle</button>}</div>
    {!cycles.length ? <div className="empty-state"><p>This program has no mesocycles yet.</p></div> : cycles.map((cycle) => <section className="card cycle-card" key={cycle.id}><div className="section-header"><div><h3>{cycle.name}</h3><p className="muted">Starts {cycle.start_date} · {cycle.mesocycle_length} days</p></div>{canPlan && <div className="actions"><button className="btn btn-outline btn-sm" onClick={() => { setCopyCycle(cycle); setTargetProgram(row.id); setName(`${cycle.name} copy`); setIncludeExecuted(false); }}>Copy</button><button className="btn btn-outline btn-sm" onClick={() => { setName(''); setWorkoutCycle(cycle.id); }}>Add workout</button></div>}</div>
      {cycle.summary && <div className="summary-strip"><span>Strength volume: {cycle.summary.strength.planned_volume} planned / {cycle.summary.strength.actual_volume} actual</span><span>Cardio time: {cycle.summary.cardio.planned_duration_seconds}s planned / {cycle.summary.cardio.actual_duration_seconds}s actual</span></div>}
      {!cycle.workouts.length ? <p className="muted">No workouts</p> : <div className="workout-list">{cycle.workouts.map((workout) => <Link className="workout-row" key={workout.id} to={`/programs/${programId}/workouts/${workout.id}`}><span>{workout.name}</span><span className="muted">Day +{workout.day_offset}</span></Link>)}</div>}
    </section>)}
    <FormModal show={cycleModal} onHide={() => setCycleModal(false)} title="Add mesocycle" onSubmit={addCycle} submitDisabled={!name.trim()}><div className="form-group"><label>Name</label><input value={name} onChange={(e) => setName(e.target.value)} /></div><div className="form-group"><label>Start date</label><input type="date" value={startDate} onChange={(e) => setStartDate(e.target.value)} /></div></FormModal>
    <FormModal show={Boolean(workoutCycle)} onHide={() => setWorkoutCycle(null)} title="Add workout" onSubmit={addWorkout} submitDisabled={!name.trim()}><div className="form-group"><label>Name</label><input value={name} onChange={(e) => setName(e.target.value)} /></div><div className="form-group"><label>Day offset</label><input type="number" min="0" value={dayOffset} onChange={(e) => setDayOffset(Number(e.target.value))} /></div></FormModal>
    <FormModal show={copyProgram} onHide={() => setCopyProgram(false)} title="Copy program" onSubmit={async (e) => { e.preventDefault(); if (!workspaceId) return; const copy = await programsApi.copy(workspaceId, row.id, { name, targetOwnerUserId: targetOwner, includeExecutedValues: includeExecuted }); setCopyProgram(false); navigate(`/programs/${copy.id}`); }} submitDisabled={!name.trim() || !targetOwner}><div className="form-group"><label>Name</label><input value={name} onChange={(e) => setName(e.target.value)} /></div><div className="form-group"><label>Owner</label><select value={targetOwner} onChange={(e) => setTargetOwner(e.target.value)}>{members.filter((m) => m.status === 'active').map((m) => <option key={m.user_id} value={m.user_id}>{m.display_name} ({m.role})</option>)}</select></div><label className="form-check"><input type="checkbox" checked={includeExecuted} onChange={(e) => setIncludeExecuted(e.target.checked)} /> Include executed values and athlete notes</label></FormModal>
    <FormModal show={Boolean(copyCycle)} onHide={() => setCopyCycle(null)} title="Copy mesocycle" onSubmit={async (e) => { e.preventDefault(); if (!workspaceId || !copyCycle) return; await programsApi.copyMesocycle(workspaceId, row.id, copyCycle.id, { targetProgramId: targetProgram, name, includeExecutedValues: includeExecuted }); setCopyCycle(null); await load(); }} submitDisabled={!targetProgram}><div className="form-group"><label>Name</label><input value={name} onChange={(e) => setName(e.target.value)} /></div><div className="form-group"><label>Destination program</label><select value={targetProgram} onChange={(e) => setTargetProgram(e.target.value)}>{programs.map((p) => <option key={p.id} value={p.id}>{p.name} — {p.owner_name}</option>)}</select></div><label className="form-check"><input type="checkbox" checked={includeExecuted} onChange={(e) => setIncludeExecuted(e.target.checked)} /> Include executed values and athlete notes</label></FormModal>
    <ConfirmModal show={deleteOpen} onHide={() => setDeleteOpen(false)} title="Delete program" message="Delete this independent program and all mesocycles, workouts, and sets?" onConfirm={async () => { if (workspaceId) { await programsApi.remove(workspaceId, row.id); navigate('/'); } }} />
  </>;
}
