/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false --strict-vars=false worker/bindings.generated.d.ts` (hash: 4348ccbd0a673465531eeb5b7821db63)
interface __BaseEnv_Env {
	DB: D1Database;
	APP_ENV: string;
	LOCAL_AUTH_ENABLED: string;
	DEV_IDENTITY_SWITCH_ENABLED: string;
	DEV_IDENTITY_SWITCH_EMAIL: string;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./index");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "APP_ENV" | "LOCAL_AUTH_ENABLED" | "DEV_IDENTITY_SWITCH_ENABLED" | "DEV_IDENTITY_SWITCH_EMAIL">> {}
}
