/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false --strict-vars=false worker/bindings.generated.d.ts` (hash: 6993b4c327a997c8844dd9d56cfaffef)
interface __BaseEnv_Env {
	DB: D1Database;
	APP_ENV: string;
	LOCAL_AUTH_ENABLED: string;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./index");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "APP_ENV" | "LOCAL_AUTH_ENABLED">> {}
}
